# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    stdlib: 
      repo: "puppetlabs/stdlib"
      ref: "8.1.0"
    python: 
      repo: "puppet/python"
      ref: "6.4.0"
    epel: 
      repo: "puppet/epel"
      ref: "3.1.0"
    puppetlabs-yumrepo_core: 
      repo: "puppetlabs/yumrepo_core"
      ref: "1.1.0"
    firewalld: 
      repo: "puppet/firewalld"
      ref: "4.4.0"
    augeas_core:
      repo: "puppetlabs/augeas_core"
      ref: "1.2.0"
    postgresql: 
      repo: "puppetlabs/postgresql"
      ref: "7.5.0"
    apt: 
      repo: "puppetlabs/apt"
      ref: "8.3.0"
    concat: 
      repo: "puppetlabs/concat"
      ref: "7.1.1"

